### PR TITLE
controllers: reset page on new query adddition

### LINKED ISSUE #59: page parameter is kept when doing a new search
When performing a new search, the search parameter is always kept. So if the search is more restrictive we end up in a page with no results.

search2

### PR DESCRIPTION
**Pull request by drjova**
* FIX Fixes an issue with page parameter which is kept when a new search
  requested. (closes #59)

Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by drjova** [comment]
ping @jmartinm

**Comment by jmartinm** [comment]
Tested it locally. Works for me :+1:

**Comment by drjova** [comment]
is it something wrong with coveralls?

**Comment by jmartinm** [comment]
> is it something wrong with coveralls?

It was down all day yesterday. I think if you close and reopen this PR it will run again both Travis and coveralls and might be fine.

**Comment by drjova** [comment]
@jmartinm thanks, I'll try it

**Pull request closed without merging**
