### PR TITLE
global: improved structure and facets addition

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@drjova it looks good. Do we need to bump the version because of file renaming (e.g. `0.1.0`)?

**Comment by drjova** [comment]
Yes sure!

**Comment by jirikuncar** [comment]
Please bump the version number in `package.json` and update copyright years in the files you have modified. Then we can :shipit: Thanks!

**Comment by drjova** [comment]
@jirikuncar done!

**Pull request merged**
