### PR TITLE
directive: initilization request duplication

### LINKED ISSUE #42: global: multiple request on initialization

### PR DESCRIPTION
**Pull request by drjova**
* FIX Fixes duplicate request issue on initilization. (closes #42)

Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by drjova** [comment]
rebased!

**Comment by lnielsen** [comment]
Using this PR I still have two requests:

```
"GET /api/records/?page=1&q=test&size=20 HTTP/1.1" 200 -
"GET /api/records/?page=1&q=test&size=20&sort=best_match HTTP/1.1" 200 -
```

This happens when using the search from the front-page where only ``/search?q=test`` is sent.

**Comment by drjova** [comment]
yep the extra `sort` request will be fixed with https://github.com/inveniosoftware/invenio-search-js/issues/44

**Comment by lnielsen** [comment]
It doesn't happen if I add sort into URL ``/search?q=test&sort=...`` - however, then the REST API can't decide which sort method to use  when the sort parameter isn't defined

**Comment by drjova** [comment]
True true, it doesn't happen because the `invenio-search-select-box` doesn't change the `sort` parameter from `undefined` to `default`

**Comment by lnielsen** [comment]
Got it :-)

**Pull request merged**
