### PR TITLE
directives: make range directive display large ranges better

### PR DESCRIPTION
**Pull request by nikofil**
* Makes text slanted to improve visibility when texts overlap.

* Increases the margin on the selection bar.

Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>

### CODE REVIEW

**Comment by nikofil** [comment]
2016-06-01-132050_3600x1200_scrot

**Comment by egabancho** [comment]
Do you think we could also remove the hard coded height and width? https://github.com/inveniosoftware/invenio-search-js/blob/master/src/invenio-search-js/invenioSearch.module.js#L1370

**Comment by nikofil** [comment]
These are overridden through the directive options, they are defaults in case the user doesn't supply a height/width. Should I remove them anyway?

**Comment by egabancho** [comment]
I think fixed defaults are not a good idea in general, specially if we want the range to be displayed nicely in several resolutions
--
cc @drjova

**Comment by drjova** [comment]
IMHO in general we need the default for out-of-the-box solution, but especially for ``width`` option it might be better to add a more responsive approach.

**Comment by drjova** [comment]
@nikofil could you please check why is failing?

**Comment by lnielsen** [comment]
One thing, wouldn't it be more easily readable if the years where horizontal?

**Comment by egabancho** [comment]
It might get a bit messy specially for smaller ranges, the years might overlap faster than now. 
We can see how it looks if we put the graph in vertical instead ...

**Pull request merged**
