### PR TITLE
global: dev dependencies update

### LINKED ISSUE #78: nodejs v7.1.0 errors on gulp commands
Mac OS with nodejs v7.1.0

When I run any gulp command, like `npm run test` the following error happens:

```javascript
/Users/jmartinm/.virtualenvs/invenio3/src/invenio-search-js/node_modules/karma/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/jmartinm/.virtualenvs/invenio3/src/invenio-search-js/node_modules/karma/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jmartinm/.virtualenvs/invenio3/src/invenio-search-js/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:573:32)
```

Which is caused by old `karma` using functions deprecated in newer Nodejs (similar to https://github.com/LearnBoost/websocket.io/issues/55).

### PR DESCRIPTION
**Pull request by jmartinm**
* Updates dev dependencies to support NodeJS 7.x. (closes #78)

Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

### CODE REVIEW

**Comment by drjova** [comment]
LGTM

**Comment by drjova** [comment]
@jmartinm just one small thing, could you please update the travis node versions 
https://github.com/inveniosoftware/invenio-search-js/blob/master/.travis.yml#L32?

According to https://github.com/nodejs/LTS#lts-schedule we can leave only the latest releases https://nodejs.org/en/download/releases:

- 0.12
- 4.6.2
- 5.12.0
- 6.9.1
- 7.1.0

Thanks :)

**Comment by jmartinm** [comment]
@drjova just submitted the changes with the new Travis matrix. It makes sense to at least test 7.1.0 since that was the point of this PR :P

Let's see if it passes correctly.

**Comment by drjova** [comment]
🎉

**Pull request merged**
