### PR TITLE
Release v1.2.1

### PR DESCRIPTION
**Pull request by drjova**

### CODE REVIEW

**Comment by lnielsen** [comment]
Was it supposed to be closed?

**Comment by drjova** [comment]
yes :)

**Comment by nharraud** [comment]
Yes it is replaced by https://github.com/inveniosoftware/invenio-app-ils/pull/38

**Comment by nharraud** [comment]
Both solutions are a kind of hack but the one in invenio-app-ils will not impact every service using invenio.

**Pull request closed without merging**
