### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by krzysztof**

### CODE REVIEW

**Comment by krzysztof** [comment]
updated badges to NPM package

**Comment by switowski** [comment]
We are not adding the license header to the `examples` documentation (https://raw.githubusercontent.com/inveniosoftware/invenio-search-js/release-1.0.0/examples/tutorials/1_started.md) ?

**Comment by krzysztof** [comment]
MAINTAINERS should be removed
secret stays as before for NPM travis settings
.md files should have rst-style headers

**Comment by switowski** [comment]
Done, please disregard the incorrect ordering of commits in GitHub (it appears that my commit is after the release commit, but actually the ordering is fine, the release commit is the last commit in this PR).

**Comment by switowski** [comment]
Can someone else take another look if everything is fine? @diegodelemos , @slint ?

**Comment by zzacharo** [comment]
@krzysztof there is a typo here https://github.com/inveniosoftware/invenio-search-js/blob/f69bbcc2368cec8fd0922fc825cef76f08f150e8/src/invenio-search-js/templates/facets.html#L9 (getValues(key)-> getValues(aggr.key)) from the previous release can you integrated to this release?

**Comment by krzysztof** [comment]
@zzacharo About https://github.com/inveniosoftware/invenio-search-js/pull/119#issuecomment-375277604 looks like it. It was a template that's usually overwritten, but it should be fixed, can you push to this branch (release-1.0.0)?

**Comment by krzysztof** [comment]
Good catch https://github.com/inveniosoftware/invenio-search-js/pull/119#pullrequestreview-106099929 :smile:

**Pull request merged**
